backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

site_url: https://david-gatsby-cms.netlify.app/
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/section1/index.md"
        label: "Section1 Page"
        name: "section1"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}          
          - {label: Background_image, name: background_image, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Second title, name: second_title, widget: string}
          - {label: Identifier, name: identifier, widget: "hidden"}
          - {label: Achievements, name: achievements, widget: list,fields: [{label: Text, name: text, widget: string}]}
          - {label: Booking, name: booking, widget: string}
          - {label: Description1, name: description1, widget: string}
          - {label: All Speaking topics link, name: speaking_topics_link, widget: string}
          - {label: Strong text, name: strong_text, widget: string}
          - {label: Description2, name: description2, widget: string}
      - file: "src/pages/section2/index.md"
        label: "Section2 Page"
        name: "section2"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Identifier, name: identifier, widget: "hidden"}
          - {label: Testimonials, name: testimonials, widget: list,fields: [{label: Author, name: author, widget: string},{label: Quote, name: quote, widget: string}]}